name: Weekly Branch Activity Check

on:
  workflow_call:
    secrets:
      passed_github_token: 
        required: true



jobs:
  check-github-context:
    runs-on: ubuntu-latest
    steps:
    - name: print context
      run: |
        echo "github.repository = ${{ github.repository }}"
        echo "current repo = ${{ github.event.repository.name }}"
        echo "this event name = ${{ github.event_name }}"



  check-branch-activity:
    runs-on: ubuntu-latest
    if: github.event_name == 'schedule'
    outputs:
      has_activity: ${{ steps.check_activity.outputs.has_activity }}
    steps:

    - name: Check branch activity
      id: check_activity
      run: |
        # Check branche deletetion activities in the last week

        # Github API query doc: https://docs.github.com/en/rest/repos/repos?apiVersion=2022-11-28#list-repository-activities
        query="time_period=week&activity_type=branch_deletion"

        branches=$(curl -s \
          -H "Authorization: token ${{ secrets.passed_github_token }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          -H "Accept: application/vnd.github+json" \
          "https://api.github.com/repos/${{ github.repository }}/activity?$query" | \
          jq -r '[.[] | .ref]')

        if [ "$branches" == "[]" ]; then
          echo "No branches were deleted in the last week, skipping the clean-up job."
          echo "has_activity=false" >> $GITHUB_OUTPUT
        else
          echo "Some branches were deleted in the last week, run the clean-up job."
          echo "has_activity=true" >> $GITHUB_OUTPUT
        fi



  intensive-work:
    runs-on: ubuntu-latest
    needs: [check-branch-activity]
    # use always() to ensure the job runs even if the previous job is skipped
    if: |
      always() &&
      (
      needs.check-branch-activity.outputs.has_activity == 'true' ||
      github.event_name == 'workflow_dispatch'
      )
    steps:
    - name: Do intensive work
      run: |
        echo "Performing intensive work..."
        echo "Triggered by type: ${{ github.event_name }}"
        echo "Branch activity: ${{ needs.check-branch-activity.outputs.has_activity }}"
