name: Weekly Branch Activity Check

on:
  workflow_dispatch:
  # schedule:
  #   # every hour
  #   - cron: '0 * * * *'


jobs:
  check-branch-activity:
    runs-on: ubuntu-latest
    if: github.event_name == 'schedule'
    outputs:
      has_activity: ${{ steps.check_activity.outputs.has_activity }}
    steps:

    - name: Check branch activity
      id: check_activity
      run: |
        # List some branches deleted in the last week

        # Github API query doc: https://docs.github.com/en/rest/repos/repos?apiVersion=2022-11-28#list-repository-activities 
        query="time_period=week&activity_type=branch_deletion"

        branches=$(curl -s \
          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          -H "Accept: application/vnd.github+json" \
          "https://api.github.com/repos/${{ github.repository }}/activity?$query" | \
          jq -r '[.[] | .ref]')


        echo "Branches: $branches"
        if [ "$branches" == "[]" ]; then
          echo "has_activity=false" >> $GITHUB_OUTPUT
        else
          echo "has_activity=true" >> $GITHUB_OUTPUT
        fi



  intensive-work:
    runs-on: ubuntu-latest
    needs: [check-branch-activity]
    if: |
      always() && 
      (
      needs.check-branch-activity.outputs.has_activity == 'true' || 
      github.event_name == 'workflow_dispatch'
      )
    steps:
    - name: Do intensive work
      run: |
        echo "Performing intensive work..."
        echo "Triggered by type: ${{ github.event_name }}"
        echo "Branch activity: ${{ needs.check-branch-activity.outputs.has_activity }}"
