name: GitHub ENV passing
on:
  push:
    branches:
      - main

jobs:
    make_env:
        runs-on: ubuntu-latest
        outputs:
            OUT_VAR: ${{ steps.set-env.outputs.OUT_VAR }}
            A_ENV_VAR: ${{ steps.read-env.outputs.A_ENV_VAR }}
        steps:
            - name: Set up environment variables
              id: set-env
              run: |
                echo "OUT_VAR=I am OUT" >> $GITHUB_OUTPUT
            - name: read env
              id: read-env
              run: |
                if [[ -f con.config ]]; then
                    cat 'con.config' >> $GITHUB_OUTPUT
                else
                    echo "con.config not found"
                fi
    

    use_env:
        needs: make_env
        runs-on: ubuntu-latest
        steps:
            - name: Use the output
              run: |
                echo "The value of the OUT_VAR variable is ${{ needs.make_env.outputs.OUT_VAR }}"
                echo "The value of the A_ENV_VAR variable is ${{ needs.make_env.outputs.A_ENV_VAR }}"
