name: GitHub ENV passing
on:
  workflow_dispatch:

jobs:
    make_env:
        outputs:
            ENV_VAR: ${{ steps.set_env.outputs.ENV_VAR }}
            OUT_VAR: ${{ steps.set_env.outputs.OUT_VAR }}
        runs-on: ubuntu-latest
        steps:
            - name: Set up environment variables
                id: set_env
                run: |
                    echo "ENV_VAR=I am ENV" >> $GITHUB_ENV
                    echo "OUT_VAR=I am OUT" >> $GITHUB_OUTPUT
    

    use_env:
        needs: make_env
        runs-on: ubuntu-latest
        steps:
            - name: Use the output
              run: |
                echo "The value of the ENV_VAR variable is ${{ needs.make_env.outputs.ENV_VAR }}"
                echo "The value of the OUT_VAR variable is ${{ needs.make_env.outputs.OUT_VAR }}"
