name: Export Env Variables

on:
    workflow_dispatch:

jobs:
  export-env-vars:
    runs-on: ubuntu-latest

    steps:
    
    - name: Set and export environment variables
      shell: bash
      env:
        MEND_ADDITIONAL_VARS: ${{vars.MEND_ADDITIONAL_VARS}}

      run: |
        # normalize newlines, force unix style
        ADDITIONAL_VARS=$(echo "$MEND_ADDITIONAL_VARS" | sed 's/\r//g')


        old_ifs="$IFS"
        # Set IFS to newline to split the variable by lines
        IFS=$'\n'

        for VAR in $ADDITIONAL_VARS; do
          # Validate the variable format (KEY=VALUE) and reject anything else
          if [[ "$VAR" =~ ^[a-zA-Z_][a-zA-Z0-9_]*=.*$ ]]; then
            # Extract variable name and value
            VAR_NAME=$(echo "$VAR" | cut -d= -f1)
            VAR_VALUE=$(echo "$VAR" | cut -d= -f2-)

            # Prevent environment variable overwriting (pollution)
            if [ -z "${!VAR_NAME}" ]; then
              # If not exists, declare and export the variable
              # declare is more safe than export, because it validates the variable name format
              declare -x "$VAR_NAME=$VAR_VALUE"
              echo "$VAR_NAME=$VAR_VALUE" >> $GITHUB_ENV
              echo "Exported: $VAR_NAME=$VAR_VALUE"
            else
              echo "Warning: Variable $VAR_NAME already exists and will not be overwritten."
            fi
          else
            echo "Warning: Invalid environment variable format: $VAR"
          fi
        done

        # restore IFS
        IFS="$old_ifs"

    - name: Show exported environment variables
      run: |
        echo "WS_MAVEN_RUNPRESTEP: $WS_MAVEN_RUNPRESTEP"
        echo "WS_ARTIFACTORY_ENABLESCAN: $WS_ARTIFACTORY_ENABLESCAN"
        echo "WS_ADD: $WS_ADD"
        echo "WS_NOPE: $WS_NOPE"
        echo "WS_NOP: $WS_NOP"
